name: CI Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
      - uses: actions/checkout@v4
      - name: test successfully builds (40 pts)
        if: ${{ !cancelled() }}
        run: |
          make clean
          make
      - name: Task 1 initializeMemory() member function (10 pts)
        if: ${{ !cancelled() }}
        run: |
          make
          ./test --list-test-names-only [task1] | grep . && ./test [task1]
      - name: Task 2 translateAddress() member function (10 pts)
        if: ${{ !cancelled() }}
        run: |
          make
          ./test --list-test-names-only [task2] | grep . && ./test [task2]
      - name: Task 3 peekAddress() and pokeAddress() member functions (10 pts)
        if: ${{ !cancelled() }}
        run: |
          make
          ./test --list-test-names-only [task3] | grep . && ./test [task3]
      - name: Task 4 fetch() member function (5 pts)
        if: ${{ !cancelled() }}
        run: |
          make
          ./test --list-test-names-only [task4] | grep . && ./test [task4]
      - name: Task 5 execute() member function (10 pts)
        if: ${{ !cancelled() }}
        run: |
          make
          ./test --list-test-names-only [task5] | grep . && ./test [task5]
      - name: Task 6 execute*() member functions (10 pts)
        if: ${{ !cancelled() }}
        run: |
          make
          ./test --list-test-names-only [task6] | grep . && ./test [task6]
      - name: Task 7 full hypothetical machine tests (5 pts)
        if: ${{ !cancelled() }}
        run: |
          make
          ./test --list-test-names-only [task7] | grep . && ./test [task7]
      - name: system tests
        if: ${{ !cancelled() }}
        run: |
          make
          ./scripts/run-system-tests
